### ISSUE TITLE
Is the previous Chinese version taken down?

### ISSUE THREAD

**Issue by offmike** [CT-ABT/Also-as-a-mainland-Chinese-why-do-I-resolutely-oppose-Google-s-dragonfly-project#1]
Just curious about the reason, there were some interesting discussions.

**Comment by CT-ABT** [comment]
Thanks for your asking.

**No.**

It wasn’t taken down by any forces. It was deleted by myself.

I had some bad moments back then and I reckoned that everything is meaningless, so I deleted it. That feeling has become very often by now and has nothing to do with the essay I wrote or the comments here.

I then felt sorry about it for that all of you have chosen to support me. Therefore I re-wrote this essay today. And yet I’m still not in the right mood, and after several times of giving-up thoughts, the essay now can be said as re-composed (in a way…?). But I cannot give you my word of not re-deleting it in the future.

Sorry about that, truly. The feeling of ‘everything is meaningless’ is striking me every now and then and will make me feel very downtrodden. Sorry!

**Comment by offmike** [comment]
Thank you for replying and writing a such long essay.

Many Hong Kong people share the same feeling as you for what happened recent years.
Nothing has been changed after different protests, the situation is even getting worse.
It is like there is a force to prohibit changes until everyone is giving up.

Changing human behaviour is really hard, even open minded people cannot make the switch easily due to long built habits.

Support is giving to what you have done, not for putting pressure on you, you don't owe anyone.
No need to push yourself too much, we all live on a small planet, nothing is big enough to worry.
Smile face is the strongest weapon for a long fight. 😊

I am closing this as the question is answered.

**Comment by CT-ABT** [comment]
Hi @offmike ,

Nah…I’m just suffering from some kind of depression. And that’s personal, not ‘politital’. For years, once I jump out of a machine-like routinely life cycle, I’ll feel very upset and downtrodden, that everything is meaningless, like I’ve exhausted my happiness and energies. (And I’ll get less upset if I try to make my every day the same routine, like a machine.) I don’t know what is happening to me, but anything that can bring me a little excitement will strike me with huge upset after that.
