### ISSUE TITLE
问题的根源在哪里？

### ISSUE THREAD

**Issue by Neo-Zhixing** [CT-ABT/Also-as-a-mainland-Chinese-why-do-I-resolutely-oppose-Google-s-dragonfly-project#14]
不去解决问题的根源，一百个Google也没有用。

眼睁睁地看着问题恶化而甘愿去做沉默的大多数，最后我们只能成为神仙打架的牺牲品。遇到政府的censorship，明知他们可以轻易mute我们的声音，不去上街游行，却甘愿在家里当一个文静优美的键盘侠。

30年前学生们的精神都去了哪里? 

一个坦克人倒下了，千千万万个坦克人也自愿倒下了。期望Google和其他外部力量来拯救我们，却不使用自己的力量去推动政治变革。

钝刀子割肉也得有个头。是时候采取一些行动了吧。

**Comment by CT-ABT** [comment]
^_^

实际上，作为一名中右翼的自由意志主义者，我是反对左派做派的。所以包括上街游行之类的行为我都是反对的，并且认为上街游行改变不了什么，或者只会变得更坏。

所以我主推「不合作」（无论是「公民不合作」 (civil disobedience) 还是「不合作运动」 (non-cooperation) 等等），也即冷静、不聚众地坚定而持久地死磕下去。我始终认为每一个人都能够坚守、捍卫自己的底线，拿出死磕的精神——不煽动情绪、不激烈言辞，但却坚定、持久地坚守自己的价值观，比大家蜂拥而上的“革命”能够达到的效果要好太多。不对，实际上，我从不认可任何“革命”，并认为任何“革命”都只能越“革”越坏。

**Comment by CT-ABT** [comment]
所以我通篇其实也在传达一个观点，那就是如果一件事情是不对的，那么就不要去做。如果别人做了一件不对的事情让你屈服，你也不要妥协。就这么简单。无论是对公司还是对个人。无需奋起抗争、摇旗呐喊，只要不妥协、不合作，事情就成了。

**Comment by Neo-Zhixing** [comment]
作为屁民我们并没有不合作的权利。你在某乎上发表文章被删，有不合作的权力吗？电视和门户网站刊登主旋律文章，你有不合作的权力吗？只要沉默的大多数继续沉默，社会的主体总是合作的，并且对现状感到满意。作为喧哗的一小撮，你想要带来改变，只能更加喧哗，去代替沉默的大多数来发出声音。

Demonstration 或许改变不了什么，但是它能够使当权者认识到，你这么做是不行的，人们对此感到愤怒，社会变得不稳定，你不能这样为所欲为。如果你只是安静地“当个键盘侠”， 那么当权者发现诶我这么做好像也没啥后果，所以他们就会更加肆无忌惮。

**Comment by CT-ABT** [comment]
@Neo-Zhixing 希望您还是多了解一下再说话。我觉得您既不了解这些概念，也不了解您口中的“当权者”是如何对待这些概念的持有者的。去了解一下吧，不要想当然地发表言论，好吗？

另外：虽然并非是针对您，而且您或者任何人也可以从鄙人的 twitter 上查知。虽然我是“中间偏右”的自由意志主义者，但我对一切左派或者左派思想／行径是恨之入骨的。所以我觉得我们也没有必要再讨论下去了，话不投机半句多。

**Comment by CT-ABT** [comment]
谁惯得你这坏毛病啊，想关 issue 就关 issue, 想删评就删评？
![](http://hiberna.memorata.me/ud/deleted_comment_01.png)

**Comment by Neotoxin4365** [comment]
说是“我们需要更多的声音”，但是当遇到跟自己不同的观点时，“话不投机半句多”。不但block我，还把关闭的issue重新打开2次，并截图记录其他人的评论，我认为这是十分不尊重的行为。

特地注册了这个throwaway账户，我希望你能关闭并删除这个issue。我不想让这样一个issue去污染我的时间线。

**Comment by CT-ABT** [comment]
@Neotoxin4365 少在这里混淆视听了，我 block 你是因为你两次关闭这个 issue. 在我重开之后马上又关闭，才 block 了你。
之后你删除自己关闭 issue 的记录，还删评论，呵呵。

继续 block 你就是了。

**Comment by Neotoxin4346** [comment]
大概是你对GitHub的流程不太熟悉，GitHub是这样的：一个问题讨论完之后，这个issue就会被关闭，表示这个问题已经处理完了。此时issue仍然留在这个repository中，对所有人可见。

重新打开别人关闭的issue，是一种非常不尊重的行为，因为这意味着你正在强迫别人参加你的讨论。所有open的issue都会留在我的客户端的panel上，表示这是一个还需要去处理的问题。既然你已经表达了不想继续讨论的意思，我才去关闭这个issue。现在你又去重新打开issue，不是强迫我回复你“话不投机半句多”的评论吗？

总而言之，交谈进行到此已经没有进行的必要，请你关闭并删除这个issue，谢谢。这是删除issue的教程：https://help.github.com/articles/deleting-an-issue/

**Comment by CT-ABT** [comment]
@Neotoxin4346 抱歉，「话不投机半句多」是表示我不想跟你讨论了。不是表示这个 issue 可以关闭了。这些 issue 都是所有人可以讨论的，又不是每个 issue 只针对 repo 主和 issue 主之间的对话。

还是说，在你两次关闭这个 issue 之前，我没有 block 你，你当时依旧可以继续发言。是你非要关闭 issue 才 block 你的。

并且，我会一直保持开启这个 issue. 也会一直 block 你。

请继续。当个 spam 发射机很有趣么？
