### ISSUE TITLE
所以终极动机是啥？

### ISSUE THREAD

**Issue by riaqn** [CT-ABT/Also-as-a-mainland-Chinese-why-do-I-resolutely-oppose-Google-s-dragonfly-project#3]
我没仔细看，请作者能不能简单概括下你的观点的动机是啥？是为了中国网民好？还是为了全世界网民好？还是单纯守卫你的价值观？

**Comment by SCLeoX** [comment]
我没仔细看你的问题，但我觉得你的问题毫无价值。

**Comment by remrait** [comment]
中国大陆并不是用不了google，只是不会翻墙的人用不了google。
google退出中国大陆，而中国大陆百度等公司的恶劣，会促进更多的人翻墙，并且在没有审查的google中发现真相，打破中共的谎言统治。
如果google返回中国大陆，那么经过审查的google并不能给大陆人带来真相，反而作为审查的帮凶，断绝了大陆人翻墙了解真相的机会。

**Comment by CT-ABT** [comment]
@remrait 
其实我把文章写得这么绕确实有避免顺带谴责中国大陆地区政府之作为的意思，尽管这层「避免」很难，但我感觉还是差不多做到了。因为我不想掺杂太多其他的内容，而是单纯想要说明白一件事情：
对于没有犯错的一方，为什么要要求他们妥协？
至于其他的，Google 妥协的措施是什么、对不对，以及中国大陆地区政府是否应该封锁 Google, 我都懒得去说了 :) 因为我发现现在大家连是非都不分了——Google 做错了什么呢，要人家上赶着舔着去妥协？

**Comment by riaqn** [comment]
@remrait 博主很明显已经走出了效用主义的低级趣味，走向了绝对道德的高地。

**Comment by CT-ABT** [comment]
@remrait 我不得不怀疑您的阅读能力有问题。

**Comment by takahashi-wwv** [comment]
@CT-ABT repo主好像at错人了。

**Comment by CT-ABT** [comment]
> @CT-ABT repo 主好像 at 错人了。

是的！mea culpa！已修正！像被误 @ 的那位道歉！

**Comment by Z-Y00** [comment]
他说的是康德的绝对命令，repo主的逻辑确实是康德的这种思想，所举的例子也是很多康德绝对命令的支持者所使用的（即repo主所用的器官捐献，电车问题）
PS. 本人也支持康德的这种观点

GengYu Rao

________________________________

**Comment by CT-ABT** [comment]
@Z-Y00 这些我都不懂，哈哈。你说的好深奥。
器官捐献那个真的是我自己想的，电车问题是原 Po 文者在其文章中引用并表示他会选择轧死一人，我才在我的文章里加以反驳的。其实我并不认为 Google 的蜻蜓计划有多么跟电车问题相关 ：）
